name: TangledMaze
version: ${project.version}
api-version: 1.13
authors: [mightyone, spthiel, GenerousGuava]
description: intuitive visual maze generator for every shape and terrain
website: https://www.spigotmc.org/resources/tangled-maze-maze-generator-1-13.59284/

main: me.gorgeousone.tangledmaze.TangledMain

commands:
  tangledmaze:
    usage: /<command> help
    aliases: [maze, tm]
    default: op

permissions:
  tangledmaze.reload:
    description: Permission for the command /tangledmaze reload.
    default: op

  tangledmaze.build:
    description: Permission for building mazes with a maze wand.
    default: op

  tangledmaze.getwand:
    description: Permission for the command /tangledmaze wand.
    default: op

  tangledmaze.teleport:
    description: Permission for teleporting yourself back to your maze.
    default: op

  tangledmaze.backup:
    description: Permission for backing up and loading mazes.
    default: op